# Generated by Django 3.2.8 on 2022-01-24 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('Andijon', 'Andijon'), ('Namangan', 'Namangan'), ('Farg`ona', 'Farg`ona'), ('Toshkent', 'Toshkent'), ('Jizzax', 'Jizzax'), ('Samarqand', 'Samarqand'), ('Qashqadaryo', 'Qashqadaryo'), ('Surxondaryo', 'Surxondaryo'), ('Navoiy', 'Navoiy'), ('Buxoro', 'Buxoro'), ('Sirdaryo', 'Sirdaryo'), ('Xorazm', 'Xorazm'), ('Qoraqalpog`iston', 'Qoraqalpog`iston')], max_length=50)),
                ('district', models.CharField(max_length=50, verbose_name='tuman')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_price', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='jami narxi')),
                ('all_pieces', models.PositiveIntegerField(verbose_name='jami soni')),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Nomi')),
                ('icon', models.ImageField(upload_to='category_img/', verbose_name='rasmi')),
            ],
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Rang nomi')),
                ('code', models.CharField(max_length=50, verbose_name='Rang kodi')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images', verbose_name='rasmi')),
            ],
        ),
        migrations.CreateModel(
            name='PayMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_num', models.PositiveIntegerField(verbose_name='karta raqami')),
                ('card_date', models.CharField(max_length=5, verbose_name='sanasi')),
                ('card_name', models.CharField(max_length=150, verbose_name='ismi')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Nomi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='narxi')),
                ('price_off', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='aksiya %')),
                ('shipping', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='elitib berish')),
                ('style', models.CharField(blank=True, max_length=50, verbose_name='styli')),
                ('info', models.TextField(blank=True, verbose_name='malumoti')),
                ('date', models.DateField(auto_now_add=True, verbose_name='sanasi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categories', verbose_name='Kategoriyasi')),
                ('colors', models.ManyToManyField(to='api.Colors', verbose_name='rangi')),
                ('images', models.ManyToManyField(to='api.Images')),
            ],
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, verbose_name='razmeri')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.BooleanField(verbose_name='Jinsi(True=erkak)')),
                ('brithday', models.DateField(verbose_name="Tug'ilgan kuni")),
                ('phone', models.PositiveIntegerField(verbose_name='Tel raqami')),
                ('adress', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.adress')),
                ('cart', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='owner', to='api.cart')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveIntegerField(verbose_name='max 5')),
                ('message', models.TextField(verbose_name='fikr')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='sanasi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate', to='api.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(to='api.Sizes', verbose_name='olchami'),
        ),
        migrations.CreateModel(
            name='Carts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pieces', models.PositiveIntegerField(verbose_name='soni')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product', verbose_name='mahsulot')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='carts',
            field=models.ManyToManyField(blank=True, to='api.Carts'),
        ),
        migrations.AddField(
            model_name='cart',
            name='payment_method',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='api.paymethod', verbose_name='kredit kartasi'),
        ),
    ]
